"""Fix medicine table foreign key or nullable fields

Revision ID: 0ffdd78d2b51
Revises: 91dd7b5d5550
Create Date: 2025-07-12 11:13:38.966439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ffdd78d2b51'
down_revision = '91dd7b5d5550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.alter_column('pharmacist_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.alter_column('pharmacist_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
