"""Fix: add pharmacist_id with named constraint

Revision ID: 91dd7b5d5550
Revises: 
Create Date: 2025-07-12 10:30:39.590790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91dd7b5d5550'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Step 1: Add column as nullable
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacist_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_medicine_pharmacist_id', 'pharmacist', ['pharmacist_id'], ['id'])

    # Step 2: Populate pharmacist_id for existing rows
    # (Replace 1 with an existing pharmacist id in your database)
    op.execute('UPDATE medicine SET pharmacist_id = 1 WHERE pharmacist_id IS NULL')

    # Step 3: Alter column to not nullable after data fix
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.alter_column('pharmacist_id',
            existing_type=sa.Integer(),
            nullable=False)

    # Your other table alteration
    with op.batch_alter_table('pharmacist', schema=None) as batch_op:
        batch_op.alter_column('admin_approved',
               existing_type=sa.BOOLEAN(),
               nullable=True)



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    def upgrade():
     with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.alter_column('pharmacist_id',
            existing_type=sa.Integer(),
            nullable=True)  # temporarily make pharmacist_id nullable

    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.drop_constraint('fk_medicine_pharmacist_id', type_='foreignkey')
        batch_op.drop_column('pharmacist_id')

    # ### end Alembic commands ###
