"""Add pharmacist_id to medicine table

Revision ID: fc0927228c5a
Revises: 
Create Date: 2025-07-12 10:19:31.455703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc0927228c5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacist_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'pharmacist', ['pharmacist_id'], ['id'])

    with op.batch_alter_table('pharmacist', schema=None) as batch_op:
        batch_op.alter_column('admin_approved',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pharmacist', schema=None) as batch_op:
        batch_op.alter_column('admin_approved',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pharmacist_id')

    # ### end Alembic commands ###
